version: '3'

services:

  api:
    build:
      context: ./project
      dockerfile: Dockerfile
    volumes:
      - ./project:/code
    environment:
      GUNICORN_RELOAD: "False"
      LOG_LOCAL: "True" # Desabilita logging externo de IP, id
      LOGGER_SWAGGER: "False" # Desabilita logging para /docs /favicon etc
      # Apenas para uvicorn
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
      FASTAPI_RELOAD: "True"
    command: /bin/sh run_uvicorn.sh # Uvicorn sh - funciona reload
    # command: ["python3", "-m", "api"] # Uvicorn python
    ports:
      - 8080:8080
    networks:
      - backend


networks:
  backend:
    driver: bridge
