version: '3'

services:

  api:
    build:
      context: ./project
      dockerfile: Dockerfile
    volumes:
      - ./project:/project
    environment:
      GUNICORN_RELOAD: "False"
      RUNNING_ENV: "dev"
      LOG_LOCAL: "True" # External logging like IP
      LOG_LEVEL: 10
      LOGGER_SWAGGER: "False" # Unnecessary logging
      FASTAPI_ROOT_PATH: ""
      # Uvicorn logging
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
      FASTAPI_RELOAD: "True"
    command: /bin/sh run_uvicorn.sh # Uvicorn - reload
    # command: ["python3", "-m", "api"] # Uvicorn with python
    ports:
      - 8080:8080
    networks:
      - backend


networks:
  backend:
    driver: bridge
