version: '3'

services:

  api:
    build:
      context: ./project
      dockerfile: Dockerfile
    environment:
      RUNNING_ENV: "prod"
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
    driver: bridge
